using Carp.Endpoints;
using Carp.ErrorPages;
using Carp.Ledger;
using Carp.Transforms;

var builder = WebApplication.CreateBuilder(args);

// ---- Crime infrastructure ---- //
builder.Services.Configure<CrimeOptions>(builder.Configuration.GetSection("Crimes"));
builder.Services.AddSingleton<CrimeLedger>(sp => new CrimeLedger(capacity: 500));
builder.Services.AddSingleton<ICrimeReporter, CrimeReporter>();

// ---- Transforms ---- //
builder.Services.AddSingleton<StatusCodeLieTransform>();
builder.Services.AddSingleton<LatencyHomeopathyTransform>();
builder.Services.AddSingleton<JwtAlgNoneTransform>();
builder.Services.AddSingleton<WeakETagTransform>();
builder.Services.AddSingleton<ECBMarkerTransform>();
builder.Services.AddSingleton<SignNullTransform>();

// ---- Error pages ---- //
builder.Services.AddSingleton<ICrimeErrorPage, Teapot418Page>();
builder.Services.AddSingleton<ICrimeErrorPage, BadGateway502Page>();
builder.Services.AddSingleton<ICrimeErrorPage, ServiceUnavailable503Page>();
builder.Services.AddSingleton<ICrimeErrorPage, GatewayTimeout504Page>();
builder.Services.AddSingleton<ICrimeErrorPage, PayloadTooLarge413Page>();
builder.Services.AddSingleton<ICrimeErrorPage, MisdirectedRequest421Page>();
builder.Services.AddSingleton<ErrorPageRouter>();

// ---- YARP ---- //
builder.Services
    .AddReverseProxy()
    .LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"))
    .AddTransforms(ctx =>
    {
        var sp = ctx.Services;
        ctx.RequestTransforms.Add(sp.GetRequiredService<LatencyHomeopathyTransform>());
        ctx.RequestTransforms.Add(sp.GetRequiredService<JwtAlgNoneTransform>());
        ctx.RequestTransforms.Add(sp.GetRequiredService<SignNullTransform>());
        ctx.ResponseTransforms.Add(sp.GetRequiredService<StatusCodeLieTransform>());
        ctx.ResponseTransforms.Add(sp.GetRequiredService<WeakETagTransform>());
        ctx.ResponseTransforms.Add(sp.GetRequiredService<ECBMarkerTransform>());
    });

var app = builder.Build();

// Error page middleware sits early so it can intercept any downstream blank
// error response, including those generated by YARP for unreachable backends.
app.UseMiddleware<CrimeErrorPageMiddleware>();

// Crime endpoints come BEFORE MapReverseProxy so they don't get proxied away.
app.MapCrimeEndpoints();
app.MapCaptivePortalEndpoints();
app.MapErrorPageEndpoints();
app.MapReverseProxy();

app.Run();
